# Generated by Django 3.2.4 on 2021-08-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client',
            new_name='clientLocation',
        ),
    ]
